function reply=stim_gallery(params)
%SAtb FUNCTION stim_gallery. Display a grid of images and prompt user for a typed response.
% - gallery items must all be the same image format.
% - for identical proportioal resizing to fit screen, images should all have the same dimentions in pixels.
% - output of Ask is a (string of) char, not numeric. Use str2double, str2num to convert.
%
%Params is a struct containing any needed info:
%     - params.gallerypath=strcat([mypath,stimdir,galleryname]);
%     - params.filesuffix='.jpg'; %filetype/ending of gallery itmes (they must all be the same).
%     - params.message='How many yellow bathing suits can you find?';
%     - params.fontSize=24;
%     - params.gallery_offset=60; %pixels down from top of screen.
%     - params.message_hoffset=20; %pixels right from left of screen
%     - params.message_voffset=-30; %pixels UP from top of GALLERY (not screen).
% If this isn't called w/params, then a demo can be run (w/ some editing).
%
%CHANGE LOG
% 3/10/15   - Started for use in bf1 expt (body perceptions), but turns out we won't use it.
% 9/30/15   - added params.ask (true/false) so that this can be called without asking for user input.
%%%%%%%%%%%%%%%%%%%

global w wRect %defined by init_ptb

if isequal(nargin,0) % if this mfile is not called as a subroutine
    %     - to run this demo, this script must lives in a starndard signals expt directory.
    if ismac
        Screen('Preference', 'SkipSyncTests', 1) %Yosemite breaks PTB timing.
    end
    [exptName mypath]=setdir(mfilename); %Get name of the currently running function, set current directory
    stimdir='stimuli/'; %Folder containing any stimuli not generated by PsychToolbox drawScreen routines.
    galleryname='Victorias_Secret_allswim_20150309/';
    params.gallerypath=strcat([mypath,stimdir,galleryname]);
    params.filesuffix='.jpg'; %filetype/ending of gallery itmes (they must all be the same).
    params.ask=true;
    params.message='How many yellow bathing suits can you find?';
    params.fontSize=24;
    params.gallery_offset=60; %pixels down from top of screen.
    params.message_hoffset=20; %pixels right from left of screen
    params.message_voffset=-30; %pixels UP from top of GALLERY (not screen).
    init_ptb(1,0,[255 255 255]); %Start PsychToolBox. flags=hidecursor,pause. Pause=0 since setting a custom "ready" screen in main_inits fn.
end

gallery_items=dir(strcat([params.gallerypath,'*',params.filesuffix])); %get list of all data files
numItems=length(gallery_items);
imdata=imread(strcat([params.gallerypath,gallery_items(1).name])); %load image file
tex=Screen('MakeTexture', w, imdata); %make texture of image w/reference to main window, w
itemRect=Screen('Rect', tex); %gets rect dimention of image

galleryRects=ArrangeRects(numItems,itemRect,[wRect(1) wRect(2)+params.gallery_offset wRect(3) wRect(4)],[]);

for ictr=1:numItems
    imdata=imread(strcat([params.gallerypath,gallery_items(ictr).name])); %load image file
    tex=Screen('MakeTexture', w, imdata); %make texture of image w/reference to main window, w
    Screen('DrawTexture', w, tex, [],galleryRects(ictr,:),[], [],[]); %draw image to backbuffer
end % for fill gallery

if params.ask==true
    reply=Ask(w,params.message,[],[],'GetChar',[wRect(1)+params.message_hoffset wRect(2)+params.message_voffset wRect(3) wRect(4)],[],params.fontSize); %includes a flip
    %    reply=eval(replyFun); %then erase by drawing text again using bgColor
    %Screen('Flip',w); waitmouse;%use if no Ask
end

if isequal(nargin,0) % if this mfile is not called as a subroutine
    cleanup;
end

end %main fn