function toggle_warnings(flag)
%% turn various ML computation warnings on/off
% esp. wrt model fitting
warning(flag,'stats:nlinfit:IterationLimitExceeded') %generated by sending null data thru sigmoid_fit.m
warning(flag,'stats:nlinfit:IllConditionedJacobian') %generated when pmetric fn is un-sigmoid. Trapped by sigmoid_fit.m
warning(flag,'stats:nlinfit:Overparameterized') %
warning(flag,'MATLAB:nearlySingularMatrix') %from call to inv() in nlinfit after bad Jacobians
warning(flag,'MATLAB:rankDeficientMatrix') %
warning(flag,'MATLAB:singularMatrix') %
warning(flag,'stats:nlinfit:ModelConstantWRTParam') %generated by bad Jacobians in sigmoid_fit_nlin
end %fn
